### ISSUE TITLE
getRecentMedia undefined method

### ISSUE THREAD

**Issue by gmeireles** [TobyRyuk/InstaCrawl#10]
![screen shot 2017-04-18 at 4 15 57 pm](https://cloud.githubusercontent.com/assets/1919508/25148766/6d572c78-2452-11e7-8f39-a66bf96ec75d.png)

**Comment by TobyRyuk** [comment]
Which version of the package are you using? Just noticed that I had forgotten to update the readme which showed instructions for requiring the alpha version of the package.

It should work fine in v1.0.0

**Comment by gmeireles** [comment]
Hi @TobyRyuk 

I'm using "dw/instacrawl": "v0.10.0-alpha" via composer
![screen shot 2017-04-19 at 10 30 29 am](https://cloud.githubusercontent.com/assets/1919508/25182531/4e8d35aa-24eb-11e7-9ebc-404288926b2a.png)

I manually include getRecentMedia function and tryed
$instagram = InstaCrawl::getRecentMedia('fuckmushroom');
dd($instagram);

but the return is null


![screen shot 2017-04-19 at 10 29 03 am](https://cloud.githubusercontent.com/assets/1919508/25182475/1277a6e0-24eb-11e7-8db3-483a693efdfb.png)

**Comment by gmeireles** [comment]
i changed my composer.json to "dw/instacrawl": "1.0" and now it worked

**Comment by TobyRyuk** [comment]
Sweet.

**Comment by gmeireles** [comment]
@TobyRyuk its possible get all media from a profile?

**Comment by TobyRyuk** [comment]
Not at the moment.

**Comment by gmeireles** [comment]
Thanks Bro!
